export const getData = () => {
  const data = [
    {
      dealerID: 1001,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1002,
      name: 'Bonhams Auctioneers and Appraisers',
      city: 'Los Angeles',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1003,
      name: 'California Numismatic Investments Inc.',
      city: 'Inglewood',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1004,
      name: 'Customized Numismatic Portfolios Inc.',
      city: 'Burbank',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1005,
      name: 'David Hall Rare Coins',
      city: 'Santa Ana',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1006,
      name: 'El Cerrito Coin Exchange',
      city: 'El Cerrito',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1007,
      name: 'G & A Coins Inc.',
      city: 'Toluca Lake',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1008,
      name: 'Gold Hill Coin',
      city: 'San Rafael',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1009,
      name: 'Frederick Lowndes Rare Coins',
      city: 'San Jose',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1010,
      name: 'GreatCollections Coin Auctions',
      city: 'Irvine',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1011,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1012,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1013,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1014,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1015,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1016,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1017,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
  ];
  return [...data];
};
