export const getData = () => {
  const data = [
    {
      dealerID: 1001,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1002,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1003,
      name: 'BBBRare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1004,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1005,
      name: 'BBBRare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1006,
      name: 'BBBRare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1007,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1008,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1009,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1010,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1011,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1012,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1013,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1014,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1015,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1016,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
    {
      dealerID: 1017,
      name: 'Americana Rare Coin Inc.',
      city: 'Sacramento',
      state: 'CA',
      zip: '95826',
      detail: 'This is the detail for the dealer',
    },
  ];
  return [...data];
};
